= Functional Utils
:toc:
:toc-placement: preamble

This project consists of some useful helper classes and interfaces, which help to write more functional Java code.

== Introduction

This project consists of some useful helper classes and interfaces, which help to write more functional Java code.

The classes are:

* link:src/main/java/de/tototec/utils/functional/FList.java[`FList`] - contains static methods returning mostly `java.util.List` s and accepting `Iterable`s and arrays, like `map`, `flatMap`, `filter`, ...
* link:src/main/java/de/tototec/utils/functional/F0.java[`F0`], link:src/main/java/de/tototec/utils/functional/F1.java[`F1`], link:src/main/java/de/tototec/utils/functional/F2.java[`F2`], ... - Interfaces representing a function with n args where n is already in the name
* link:src/main/java/de/tototec/utils/functional/Procedure0.java[`Procedure0`], link:src/main/java/de/tototec/utils/functional/Procedure1.java[`Procedure1`], link:src/main/java/de/tototec/utils/functional/Procedure2.java[`Procedure2`] - Interfaces representing a procedure with n args where n is given by the name
* link:src/main/java/de/tototec/utils/functional/Optional.java[`Optional`] - An immutable class representing an optional value
* link:src/main/java/de/tototec/utils/functional/Either.java[`Either`] - An immutable class representing either one of two values
* link:src/main/java/de/tototec/utils/functional/Tuple2.java[`Tuple2`], link:src/main/java/de/tototec/utils/functional/Tuple3.java[`Tuple3`], ... - Classes representing tuples with n args where n is given by the name

All those classes and interfaces can be used with Java 5 and above. Although by their use, your code will not get more compact, but maybe less errorprone.

// TODO: Examples

(Example will come later)

== Use with Java 8 Lambdas

Writing functional code can be much more pleasant if Java 8 Lambda expressions can be used. The function and procedure interfaces all fulfil the requirements for functional interfaces and can be thus implicitly inferred when lambda expressions are used.

== Use of Java 8 Lambdas for earlier Java Runtimes

Using the Java 8 lamdba expressions can grealty improve the functional experience. If you need to target an older Java Runtime, down to Java 5, you can still compile your code with a Java 8 compiler and afterwards postprocess the classfiles with the https://github.com/orfjackal/retrolambda[retrolambda tool]. As long as you only use the Lambda syntax but no other new API from Java 8, your code will also run in Java 7 and before.

To use Retrolambda in your Maven project, you need to add something like this (please refer also to the Retrolambda website for more up to date information):
[source,xml]
----
<plugin>
    <groupId>net.orfjackal.retrolambda</groupId>
    <artifactId>retrolambda-maven-plugin</artifactId>
    <version>1.6.1</version>
    <executions>
        <execution>
            <goals>
                <goal>process-main</goal>
                <goal>process-test</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----


== Recomendation for Editing files with Eclipse

// TODO: include list
